version: '3.8'

services:
    box:
        build:
            context: ./flask-app
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        container_name: box
        volumes:
            - './flask-app:/app'
            - './data:/data'
    tests:
        build:
            context: ./flask-app/tests
            dockerfile: Dockerfile
        container_name: tests
        volumes:
            - './flask-app:/app'
            - './data:/data'
            - './test-data:/test-data'
